# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\login.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/r/Login/index")
            .get("http://sso.12301dev.com/r/Login/index")
            .with_headers(
                **{
                    "Content-Type": "text/json;charset=UTF-8",
                }
            )
            .with_params(
                **{
                    "sys_identifier": "wj.12301.cc",
                    "account": "123933",
                    "password": "mmcs123"
                }
                )
            .validate()
            .assert_equal("status_code", 200)
            # .assert_equal('headers."Content-Type"', "text/json;charset=UTF-8")
        ),
    #     Step(
    #         RunRequest("/api/sso-authenticate")
    #         .get("http://wanju.12301dev.com/api/sso-authenticate")
    #         .with_params(
    #             **{
    #                 "token": "b9a9jBhL3w8iCKwBgLfq/or0Te9lP8LD9PElWAKH4Bk+Uos7QWMncNYzGPVRgPTGs3gQjEbp+UmUlcFXQ1DyZLXGhT2H"
    #             }
    #         )
    #         .with_headers(
    #             **{
    #                 "Host": "wanju.12301dev.com",
    #                 "Upgrade-Insecure-Requests": "1",
    #                 "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3879.400 QQBrowser/10.8.4552.400",
    #                 "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
    #                 "Referer": "http://sso.12301dev.com/?system=wj.12301.cc",
    #                 "Accept-Encoding": "gzip, deflate",
    #                 "Accept-Language": "zh-CN,zh;q=0.9",
    #                 "Cookie": "sso-redirect-url=http%3A%2F%2Fwanju.12301dev.com%2Fhome%2F; UM_distinctid=17d32cf3154119-0b171b8bbe0242-3354417a-144000-17d32cf315541e; PHPSESSID=7e8d06f316b7522739315ef7b2e04d90; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%226006982%22%2C%22first_id%22%3A%2217d32cf312c31c-04d7538421b413-3354417a-1327104-17d32cf312ef35%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%7D%2C%22%24device_id%22%3A%2217d32cf312c31c-04d7538421b413-3354417a-1327104-17d32cf312ef35%22%7D",
    #             }
    #         )
    #         .with_cookies(
    #             **{
    #                 "sso-redirect-url": "http%3A%2F%2Fwanju.12301dev.com%2Fhome%2F",
    #                 "UM_distinctid": "17d32cf3154119-0b171b8bbe0242-3354417a-144000-17d32cf315541e",
    #                 "PHPSESSID": "7e8d06f316b7522739315ef7b2e04d90",
    #                 "sensorsdata2015jssdkcross": "%7B%22distinct_id%22%3A%226006982%22%2C%22first_id%22%3A%2217d32cf312c31c-04d7538421b413-3354417a-1327104-17d32cf312ef35%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%7D%2C%22%24device_id%22%3A%2217d32cf312c31c-04d7538421b413-3354417a-1327104-17d32cf312ef35%22%7D",
    #             }
    #         )
    #         .validate()
    #         .assert_equal("status_code", 302)
    #     ),
    #     Step(
    #         RunRequest("/home/")
    #         .get("http://wanju.12301dev.com/home/")
    #         .with_params(
    #             **{
    #                 "token": "b9a9jBhL3w8iCKwBgLfq%2For0Te9lP8LD9PElWAKH4Bk%2BUos7QWMncNYzGPVRgPTGs3gQjEbp%2BUmUlcFXQ1DyZLXGhT2H"
    #             }
    #         )
    #         .with_headers(
    #             **{
    #                 "Host": "wanju.12301dev.com",
    #                 "Upgrade-Insecure-Requests": "1",
    #                 "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3879.400 QQBrowser/10.8.4552.400",
    #                 "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
    #                 "Referer": "http://sso.12301dev.com/",
    #                 "Accept-Encoding": "gzip, deflate",
    #                 "Accept-Language": "zh-CN,zh;q=0.9",
    #                 "Cookie": "UM_distinctid=17d32cf3154119-0b171b8bbe0242-3354417a-144000-17d32cf315541e; PHPSESSID=7e8d06f316b7522739315ef7b2e04d90; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%226006982%22%2C%22first_id%22%3A%2217d32cf312c31c-04d7538421b413-3354417a-1327104-17d32cf312ef35%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%7D%2C%22%24device_id%22%3A%2217d32cf312c31c-04d7538421b413-3354417a-1327104-17d32cf312ef35%22%7D",
    #             }
    #         )
    #         .with_cookies(
    #             **{
    #                 "UM_distinctid": "17d32cf3154119-0b171b8bbe0242-3354417a-144000-17d32cf315541e",
    #                 "PHPSESSID": "7e8d06f316b7522739315ef7b2e04d90",
    #                 "sensorsdata2015jssdkcross": "%7B%22distinct_id%22%3A%226006982%22%2C%22first_id%22%3A%2217d32cf312c31c-04d7538421b413-3354417a-1327104-17d32cf312ef35%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%7D%2C%22%24device_id%22%3A%2217d32cf312c31c-04d7538421b413-3354417a-1327104-17d32cf312ef35%22%7D",
    #             }
    #         )
    #         .validate()
    #         .assert_equal("status_code", 200)
    #         .assert_equal('headers."Content-Type"', "text/html")
    #     ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
